language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
  - composer install

before_script:
  - sudo apt-get install apache2